// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package saleproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestHeader struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Product struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity             int32    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type RequestField struct {
	Customer             int32      `protobuf:"varint,1,opt,name=customer,proto3" json:"customer,omitempty"`
	InvoiceNumber        string     `protobuf:"bytes,2,opt,name=invoiceNumber,proto3" json:"invoiceNumber,omitempty"`
	InvoiceDate          string     `protobuf:"bytes,3,opt,name=invoiceDate,proto3" json:"invoiceDate,omitempty"`
	Name                 string     `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string     `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	DiscountRate         float32    `protobuf:"fixed32,6,opt,name=discountRate,proto3" json:"discountRate,omitempty"`
	PaidAmount           float64    `protobuf:"fixed64,7,opt,name=paidAmount,proto3" json:"paidAmount,omitempty"`
	PaymentType          string     `protobuf:"bytes,8,opt,name=paymentType,proto3" json:"paymentType,omitempty"`
	Products             []*Product `protobuf:"bytes,9,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RequestField) Reset()         { *m = RequestField{} }
func (m *RequestField) String() string { return proto.CompactTextString(m) }
func (*RequestField) ProtoMessage()    {}
func (*RequestField) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *RequestField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestField.Unmarshal(m, b)
}
func (m *RequestField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestField.Marshal(b, m, deterministic)
}
func (m *RequestField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestField.Merge(m, src)
}
func (m *RequestField) XXX_Size() int {
	return xxx_messageInfo_RequestField.Size(m)
}
func (m *RequestField) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestField.DiscardUnknown(m)
}

var xxx_messageInfo_RequestField proto.InternalMessageInfo

func (m *RequestField) GetCustomer() int32 {
	if m != nil {
		return m.Customer
	}
	return 0
}

func (m *RequestField) GetInvoiceNumber() string {
	if m != nil {
		return m.InvoiceNumber
	}
	return ""
}

func (m *RequestField) GetInvoiceDate() string {
	if m != nil {
		return m.InvoiceDate
	}
	return ""
}

func (m *RequestField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RequestField) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RequestField) GetDiscountRate() float32 {
	if m != nil {
		return m.DiscountRate
	}
	return 0
}

func (m *RequestField) GetPaidAmount() float64 {
	if m != nil {
		return m.PaidAmount
	}
	return 0
}

func (m *RequestField) GetPaymentType() string {
	if m != nil {
		return m.PaymentType
	}
	return ""
}

func (m *RequestField) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type RawRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RawRequest) Reset()         { *m = RawRequest{} }
func (m *RawRequest) String() string { return proto.CompactTextString(m) }
func (*RawRequest) ProtoMessage()    {}
func (*RawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *RawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawRequest.Unmarshal(m, b)
}
func (m *RawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawRequest.Marshal(b, m, deterministic)
}
func (m *RawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawRequest.Merge(m, src)
}
func (m *RawRequest) XXX_Size() int {
	return xxx_messageInfo_RawRequest.Size(m)
}
func (m *RawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawRequest proto.InternalMessageInfo

func (m *RawRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GetRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int32          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Field                *RequestField  `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CreateRequest) GetField() *RequestField {
	if m != nil {
		return m.Field
	}
	return nil
}

type UpdateRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int32          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Field                *RequestField  `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UpdateRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRequest) GetField() *RequestField {
	if m != nil {
		return m.Field
	}
	return nil
}

type ActionRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int32          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ActionRequest) Reset()         { *m = ActionRequest{} }
func (m *ActionRequest) String() string { return proto.CompactTextString(m) }
func (*ActionRequest) ProtoMessage()    {}
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *ActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionRequest.Unmarshal(m, b)
}
func (m *ActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionRequest.Marshal(b, m, deterministic)
}
func (m *ActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionRequest.Merge(m, src)
}
func (m *ActionRequest) XXX_Size() int {
	return xxx_messageInfo_ActionRequest.Size(m)
}
func (m *ActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActionRequest proto.InternalMessageInfo

func (m *ActionRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ActionRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ActionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DataResponse struct {
	StatusCode           int32              `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *DataResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (m *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(m, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *DataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DataResponse) GetData() *DataResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type DataResponse_Data struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string            `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CustomerID           int32             `protobuf:"varint,4,opt,name=customerID,proto3" json:"customerID,omitempty"`
	Customer             string            `protobuf:"bytes,5,opt,name=customer,proto3" json:"customer,omitempty"`
	InvoiceNumber        string            `protobuf:"bytes,6,opt,name=invoiceNumber,proto3" json:"invoiceNumber,omitempty"`
	InvoiceDate          string            `protobuf:"bytes,7,opt,name=invoiceDate,proto3" json:"invoiceDate,omitempty"`
	PaymentType          string            `protobuf:"bytes,8,opt,name=paymentType,proto3" json:"paymentType,omitempty"`
	Products             []int32           `protobuf:"varint,9,rep,packed,name=products,proto3" json:"products,omitempty"`
	TotalGrossAmount     float64           `protobuf:"fixed64,10,opt,name=totalGrossAmount,proto3" json:"totalGrossAmount,omitempty"`
	TotalTaxAmount       float64           `protobuf:"fixed64,11,opt,name=totalTaxAmount,proto3" json:"totalTaxAmount,omitempty"`
	TotalFinalAmount     float64           `protobuf:"fixed64,12,opt,name=totalFinalAmount,proto3" json:"totalFinalAmount,omitempty"`
	GrandTotal           float64           `protobuf:"fixed64,13,opt,name=grandTotal,proto3" json:"grandTotal,omitempty"`
	DiscountRate         float32           `protobuf:"fixed32,14,opt,name=discountRate,proto3" json:"discountRate,omitempty"`
	DiscountAmount       float64           `protobuf:"fixed64,15,opt,name=discountAmount,proto3" json:"discountAmount,omitempty"`
	TotalPaidAmount      float64           `protobuf:"fixed64,16,opt,name=totalPaidAmount,proto3" json:"totalPaidAmount,omitempty"`
	CreatedDate          string            `protobuf:"bytes,17,opt,name=createdDate,proto3" json:"createdDate,omitempty"`
	CreatedBy            string            `protobuf:"bytes,18,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	LastModifiedBy       string            `protobuf:"bytes,19,opt,name=lastModifiedBy,proto3" json:"lastModifiedBy,omitempty"`
	LastModifiedDate     string            `protobuf:"bytes,20,opt,name=lastModifiedDate,proto3" json:"lastModifiedDate,omitempty"`
	RecordState          string            `protobuf:"bytes,21,opt,name=recordState,proto3" json:"recordState,omitempty"`
	ReferencedBy         int64             `protobuf:"varint,22,opt,name=referencedBy,proto3" json:"referencedBy,omitempty"`
	Currency             string            `protobuf:"bytes,23,opt,name=currency,proto3" json:"currency,omitempty"`
	Quantity             map[string]string `protobuf:"bytes,24,rep,name=quantity,proto3" json:"quantity,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DataResponse_Data) Reset()         { *m = DataResponse_Data{} }
func (m *DataResponse_Data) String() string { return proto.CompactTextString(m) }
func (*DataResponse_Data) ProtoMessage()    {}
func (*DataResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8, 0}
}

func (m *DataResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse_Data.Unmarshal(m, b)
}
func (m *DataResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse_Data.Marshal(b, m, deterministic)
}
func (m *DataResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse_Data.Merge(m, src)
}
func (m *DataResponse_Data) XXX_Size() int {
	return xxx_messageInfo_DataResponse_Data.Size(m)
}
func (m *DataResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse_Data proto.InternalMessageInfo

func (m *DataResponse_Data) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DataResponse_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataResponse_Data) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DataResponse_Data) GetCustomerID() int32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *DataResponse_Data) GetCustomer() string {
	if m != nil {
		return m.Customer
	}
	return ""
}

func (m *DataResponse_Data) GetInvoiceNumber() string {
	if m != nil {
		return m.InvoiceNumber
	}
	return ""
}

func (m *DataResponse_Data) GetInvoiceDate() string {
	if m != nil {
		return m.InvoiceDate
	}
	return ""
}

func (m *DataResponse_Data) GetPaymentType() string {
	if m != nil {
		return m.PaymentType
	}
	return ""
}

func (m *DataResponse_Data) GetProducts() []int32 {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *DataResponse_Data) GetTotalGrossAmount() float64 {
	if m != nil {
		return m.TotalGrossAmount
	}
	return 0
}

func (m *DataResponse_Data) GetTotalTaxAmount() float64 {
	if m != nil {
		return m.TotalTaxAmount
	}
	return 0
}

func (m *DataResponse_Data) GetTotalFinalAmount() float64 {
	if m != nil {
		return m.TotalFinalAmount
	}
	return 0
}

func (m *DataResponse_Data) GetGrandTotal() float64 {
	if m != nil {
		return m.GrandTotal
	}
	return 0
}

func (m *DataResponse_Data) GetDiscountRate() float32 {
	if m != nil {
		return m.DiscountRate
	}
	return 0
}

func (m *DataResponse_Data) GetDiscountAmount() float64 {
	if m != nil {
		return m.DiscountAmount
	}
	return 0
}

func (m *DataResponse_Data) GetTotalPaidAmount() float64 {
	if m != nil {
		return m.TotalPaidAmount
	}
	return 0
}

func (m *DataResponse_Data) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *DataResponse_Data) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *DataResponse_Data) GetLastModifiedBy() string {
	if m != nil {
		return m.LastModifiedBy
	}
	return ""
}

func (m *DataResponse_Data) GetLastModifiedDate() string {
	if m != nil {
		return m.LastModifiedDate
	}
	return ""
}

func (m *DataResponse_Data) GetRecordState() string {
	if m != nil {
		return m.RecordState
	}
	return ""
}

func (m *DataResponse_Data) GetReferencedBy() int64 {
	if m != nil {
		return m.ReferencedBy
	}
	return 0
}

func (m *DataResponse_Data) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *DataResponse_Data) GetQuantity() map[string]string {
	if m != nil {
		return m.Quantity
	}
	return nil
}

type RawResponse struct {
	StatusCode           int32             `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *RawResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RawResponse) Reset()         { *m = RawResponse{} }
func (m *RawResponse) String() string { return proto.CompactTextString(m) }
func (*RawResponse) ProtoMessage()    {}
func (*RawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *RawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawResponse.Unmarshal(m, b)
}
func (m *RawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawResponse.Marshal(b, m, deterministic)
}
func (m *RawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawResponse.Merge(m, src)
}
func (m *RawResponse) XXX_Size() int {
	return xxx_messageInfo_RawResponse.Size(m)
}
func (m *RawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawResponse proto.InternalMessageInfo

func (m *RawResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RawResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RawResponse) GetData() *RawResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type RawResponse_Data struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	InvoiceNumber        string   `protobuf:"bytes,2,opt,name=invoiceNumber,proto3" json:"invoiceNumber,omitempty"`
	PaymentType          []string `protobuf:"bytes,3,rep,name=paymentType,proto3" json:"paymentType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawResponse_Data) Reset()         { *m = RawResponse_Data{} }
func (m *RawResponse_Data) String() string { return proto.CompactTextString(m) }
func (*RawResponse_Data) ProtoMessage()    {}
func (*RawResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9, 0}
}

func (m *RawResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawResponse_Data.Unmarshal(m, b)
}
func (m *RawResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawResponse_Data.Marshal(b, m, deterministic)
}
func (m *RawResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawResponse_Data.Merge(m, src)
}
func (m *RawResponse_Data) XXX_Size() int {
	return xxx_messageInfo_RawResponse_Data.Size(m)
}
func (m *RawResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_RawResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_RawResponse_Data proto.InternalMessageInfo

func (m *RawResponse_Data) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *RawResponse_Data) GetInvoiceNumber() string {
	if m != nil {
		return m.InvoiceNumber
	}
	return ""
}

func (m *RawResponse_Data) GetPaymentType() []string {
	if m != nil {
		return m.PaymentType
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestHeader)(nil), "saleproto.RequestHeader")
	proto.RegisterType((*Product)(nil), "saleproto.Product")
	proto.RegisterType((*RequestField)(nil), "saleproto.RequestField")
	proto.RegisterType((*RawRequest)(nil), "saleproto.RawRequest")
	proto.RegisterType((*GetRequest)(nil), "saleproto.GetRequest")
	proto.RegisterType((*CreateRequest)(nil), "saleproto.CreateRequest")
	proto.RegisterType((*UpdateRequest)(nil), "saleproto.UpdateRequest")
	proto.RegisterType((*ActionRequest)(nil), "saleproto.ActionRequest")
	proto.RegisterType((*DataResponse)(nil), "saleproto.DataResponse")
	proto.RegisterType((*DataResponse_Data)(nil), "saleproto.DataResponse.Data")
	proto.RegisterMapType((map[string]string)(nil), "saleproto.DataResponse.Data.QuantityEntry")
	proto.RegisterType((*RawResponse)(nil), "saleproto.RawResponse")
	proto.RegisterType((*RawResponse_Data)(nil), "saleproto.RawResponse.Data")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 854 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0x96, 0xed, 0xfd, 0xc9, 0x9e, 0x8d, 0xd3, 0x30, 0xb4, 0x8d, 0xb5, 0x54, 0xd5, 0xca, 0x82,
	0x6a, 0x55, 0x89, 0xa5, 0x0a, 0x54, 0x42, 0x44, 0x42, 0x2a, 0x0d, 0x09, 0x5c, 0x50, 0x15, 0x37,
	0x3c, 0xc0, 0xd4, 0x3e, 0x29, 0xa6, 0xbb, 0xb6, 0x3b, 0x33, 0x4e, 0xd9, 0x3b, 0x1e, 0x04, 0x89,
	0x7b, 0x1e, 0x82, 0xa7, 0xe1, 0x41, 0xd0, 0x9c, 0x99, 0x5d, 0x8f, 0xbd, 0x4d, 0x88, 0x9a, 0xde,
	0xf9, 0x7c, 0x73, 0xfe, 0x7c, 0x66, 0xbe, 0xef, 0x40, 0x28, 0x51, 0x5c, 0xe4, 0x29, 0xce, 0x2b,
	0x51, 0xaa, 0x92, 0x8d, 0x24, 0x5f, 0x20, 0x7d, 0xc6, 0x9f, 0x41, 0x98, 0xe0, 0x9b, 0x1a, 0xa5,
	0xfa, 0x01, 0x79, 0x86, 0x82, 0xdd, 0x86, 0xbe, 0x2a, 0x5f, 0x63, 0x11, 0x79, 0x53, 0x6f, 0x36,
	0x4a, 0x8c, 0x11, 0x3f, 0x86, 0xe1, 0x73, 0x51, 0x66, 0x75, 0xaa, 0xd8, 0x1e, 0xf8, 0x79, 0x46,
	0xa7, 0xfd, 0xc4, 0xcf, 0x33, 0x36, 0x81, 0x9d, 0x37, 0x35, 0x2f, 0x54, 0xae, 0x56, 0x91, 0x4f,
	0xe8, 0xc6, 0x8e, 0xff, 0xf1, 0x61, 0xd7, 0xa6, 0x3f, 0xc9, 0x71, 0x41, 0xce, 0x69, 0x2d, 0x55,
	0xb9, 0x44, 0x61, 0x53, 0x6c, 0x6c, 0xf6, 0x29, 0x84, 0x79, 0x71, 0x51, 0xe6, 0x29, 0x3e, 0xab,
	0x97, 0x2f, 0x51, 0x50, 0xb6, 0x51, 0xd2, 0x06, 0xd9, 0x14, 0xc6, 0x16, 0x38, 0xe6, 0x0a, 0xa3,
	0x80, 0x7c, 0x5c, 0x88, 0x31, 0xe8, 0x15, 0x7c, 0x89, 0x51, 0x8f, 0x8e, 0xe8, 0x5b, 0x47, 0x65,
	0x28, 0x53, 0x91, 0x57, 0x2a, 0x2f, 0x8b, 0xa8, 0x6f, 0xa2, 0x1c, 0x88, 0xc5, 0xb0, 0x9b, 0xe5,
	0x32, 0x2d, 0xeb, 0x42, 0x25, 0x3a, 0xf1, 0x60, 0xea, 0xcd, 0xfc, 0xa4, 0x85, 0xb1, 0xfb, 0x00,
	0x15, 0xcf, 0xb3, 0x27, 0x4b, 0x8d, 0x44, 0xc3, 0xa9, 0x37, 0xf3, 0x12, 0x07, 0xd1, 0x55, 0x2a,
	0xbe, 0x5a, 0x62, 0xa1, 0xce, 0x56, 0x15, 0x46, 0x3b, 0xa6, 0x8a, 0x03, 0xb1, 0x39, 0xec, 0x54,
	0x66, 0x8e, 0x32, 0x1a, 0x4d, 0x83, 0xd9, 0xf8, 0x90, 0xcd, 0x37, 0x97, 0x31, 0xb7, 0x23, 0x4e,
	0x36, 0x3e, 0xf1, 0xb7, 0x00, 0x09, 0x7f, 0x6b, 0x47, 0xc8, 0x1e, 0xc1, 0xe0, 0x57, 0xba, 0x25,
	0x9a, 0xdd, 0xf8, 0x30, 0x72, 0x62, 0x5b, 0xb7, 0x98, 0x58, 0xbf, 0xf8, 0x19, 0xc0, 0x29, 0xaa,
	0xf7, 0x8e, 0xb7, 0x97, 0xed, 0xaf, 0x2f, 0x3b, 0xae, 0x20, 0x7c, 0x2a, 0x90, 0x2b, 0x7c, 0xff,
	0x94, 0x9f, 0x43, 0xff, 0x5c, 0xbf, 0x05, 0xca, 0x3a, 0x3e, 0x3c, 0xd8, 0x0e, 0xa0, 0xa7, 0x92,
	0x18, 0xaf, 0xf8, 0x0f, 0x0f, 0xc2, 0x5f, 0xaa, 0xec, 0x46, 0x25, 0x3b, 0x7f, 0xd1, 0xb4, 0x10,
	0x5c, 0xab, 0x05, 0x84, 0xf0, 0x49, 0xaa, 0x1f, 0xc9, 0x87, 0xeb, 0x60, 0xfd, 0x46, 0x83, 0xe6,
	0x8d, 0xc6, 0x7f, 0xee, 0xc0, 0xee, 0x31, 0x57, 0x3c, 0x41, 0x59, 0x95, 0x85, 0xa4, 0xe7, 0x26,
	0x15, 0x57, 0xb5, 0x7c, 0x5a, 0x66, 0x68, 0xe9, 0xe2, 0x20, 0x2c, 0x82, 0xe1, 0x12, 0xa5, 0xe4,
	0xaf, 0xd0, 0x52, 0x65, 0x6d, 0xb2, 0x47, 0xd0, 0xcb, 0xb8, 0xe2, 0xf6, 0xff, 0xee, 0x39, 0xed,
	0xb9, 0x05, 0x8c, 0x41, 0x9e, 0x93, 0xbf, 0x86, 0xd0, 0xd3, 0xa6, 0x43, 0xef, 0x51, 0xab, 0x53,
	0xff, 0x72, 0x36, 0x05, 0xdb, 0x6c, 0xba, 0x0f, 0xb0, 0xe6, 0xf5, 0x8f, 0xc7, 0xc4, 0xc4, 0x7e,
	0xe2, 0x20, 0x2d, 0x1d, 0x30, 0x64, 0xbc, 0x42, 0x07, 0x06, 0xd7, 0xd0, 0x81, 0xe1, 0xb6, 0x0e,
	0xfc, 0x3f, 0x1b, 0x27, 0x1d, 0x36, 0xf6, 0x1b, 0xe6, 0xb1, 0x87, 0xb0, 0xaf, 0x4a, 0xc5, 0x17,
	0xa7, 0xa2, 0x94, 0xd2, 0x32, 0x1e, 0x88, 0xf1, 0x5b, 0x38, 0x7b, 0x00, 0x7b, 0x84, 0x9d, 0xf1,
	0xdf, 0xad, 0xe7, 0x98, 0x3c, 0x3b, 0xe8, 0x26, 0xe7, 0x49, 0x5e, 0xf0, 0x85, 0xf5, 0xdc, 0x75,
	0x72, 0x3a, 0xb8, 0x9e, 0xe0, 0x2b, 0xc1, 0x8b, 0xec, 0x4c, 0x1f, 0x44, 0xa1, 0xd1, 0x9a, 0x06,
	0xd9, 0xd2, 0xab, 0xbd, 0x77, 0xe8, 0xd5, 0x03, 0xd8, 0x5b, 0xdb, 0xb6, 0xda, 0x2d, 0xd3, 0x57,
	0x1b, 0x65, 0x33, 0xb8, 0x45, 0xf5, 0x9f, 0x37, 0xe2, 0xb6, 0x4f, 0x8e, 0x5d, 0x58, 0xcf, 0x34,
	0x25, 0xfe, 0x67, 0x34, 0xf5, 0x8f, 0xcc, 0x4c, 0x1d, 0x88, 0xdd, 0x83, 0x91, 0x35, 0xbf, 0x5b,
	0x45, 0x8c, 0xce, 0x1b, 0x40, 0x77, 0xb4, 0xe0, 0x52, 0xfd, 0x54, 0x66, 0xf9, 0x79, 0x4e, 0x2e,
	0x1f, 0x93, 0x4b, 0x07, 0xd5, 0x93, 0x72, 0x11, 0x2a, 0x76, 0x9b, 0x3c, 0xb7, 0x70, 0xdd, 0x93,
	0xc0, 0xb4, 0x14, 0xd9, 0x0b, 0xa5, 0xdd, 0xee, 0x98, 0x9e, 0x1c, 0x48, 0xcf, 0x4a, 0xe0, 0x39,
	0x0a, 0x2c, 0x52, 0xaa, 0x79, 0x77, 0xea, 0xcd, 0x82, 0xa4, 0x85, 0x99, 0x17, 0x29, 0xb4, 0xb9,
	0x8a, 0x0e, 0xd6, 0x2f, 0xd2, 0xd8, 0xec, 0xc4, 0x59, 0x71, 0x11, 0xa9, 0xf6, 0xc3, 0xab, 0x28,
	0x35, 0xff, 0xd9, 0x3a, 0x7f, 0x5f, 0x28, 0xb1, 0x6a, 0xd6, 0xe1, 0xe4, 0x08, 0xc2, 0xd6, 0x11,
	0xdb, 0x87, 0xe0, 0x35, 0xae, 0x2c, 0xdb, 0xf4, 0xa7, 0x5e, 0xbf, 0x17, 0x7c, 0x51, 0xaf, 0xf9,
	0x66, 0x8c, 0x6f, 0xfc, 0xaf, 0xbd, 0xf8, 0x5f, 0x0f, 0xc6, 0xb4, 0x0b, 0x6e, 0xac, 0x0e, 0x5f,
	0xb4, 0xd4, 0xe1, 0x13, 0x57, 0xbc, 0x9a, 0xfc, 0xae, 0x38, 0xfc, 0x66, 0xb5, 0xc1, 0x9d, 0x91,
	0xd7, 0x99, 0xd1, 0xb5, 0xb7, 0xb7, 0xcb, 0xc9, 0x60, 0x1a, 0x74, 0x38, 0x79, 0xf8, 0xb7, 0x0f,
	0xbd, 0x17, 0x7c, 0x81, 0xec, 0x2b, 0x08, 0x12, 0xfe, 0x96, 0xdd, 0xe9, 0xb6, 0x47, 0xf2, 0x3a,
	0xb9, 0xfb, 0xee, 0xae, 0xd9, 0x11, 0x0c, 0xcc, 0x82, 0x62, 0xae, 0x28, 0xb7, 0x76, 0xd6, 0xe4,
	0xe0, 0x92, 0xcb, 0x63, 0x8f, 0x21, 0x38, 0x45, 0xd5, 0x2a, 0xd9, 0x6c, 0xcf, 0xcb, 0xc3, 0x8e,
	0x60, 0x60, 0x36, 0x54, 0xab, 0x66, 0x6b, 0x69, 0x5d, 0x19, 0x6c, 0x96, 0x4b, 0x2b, 0xb8, 0xb5,
	0x6f, 0x2e, 0x0d, 0x7e, 0x39, 0x20, 0xec, 0xcb, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x15,
	0x65, 0x2d, 0xe0, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SaleClient is the client API for Sale service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SaleClient interface {
	Raw(ctx context.Context, in *RawRequest, opts ...grpc.CallOption) (*RawResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*DataResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*DataResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*DataResponse, error)
	Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*DataResponse, error)
}

type saleClient struct {
	cc *grpc.ClientConn
}

func NewSaleClient(cc *grpc.ClientConn) SaleClient {
	return &saleClient{cc}
}

func (c *saleClient) Raw(ctx context.Context, in *RawRequest, opts ...grpc.CallOption) (*RawResponse, error) {
	out := new(RawResponse)
	err := c.cc.Invoke(ctx, "/saleproto.Sale/Raw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saleClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/saleproto.Sale/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saleClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/saleproto.Sale/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saleClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/saleproto.Sale/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saleClient) Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/saleproto.Sale/Action", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaleServer is the server API for Sale service.
type SaleServer interface {
	Raw(context.Context, *RawRequest) (*RawResponse, error)
	Create(context.Context, *CreateRequest) (*DataResponse, error)
	Get(context.Context, *GetRequest) (*DataResponse, error)
	Update(context.Context, *UpdateRequest) (*DataResponse, error)
	Action(context.Context, *ActionRequest) (*DataResponse, error)
}

// UnimplementedSaleServer can be embedded to have forward compatible implementations.
type UnimplementedSaleServer struct {
}

func (*UnimplementedSaleServer) Raw(ctx context.Context, req *RawRequest) (*RawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Raw not implemented")
}
func (*UnimplementedSaleServer) Create(ctx context.Context, req *CreateRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedSaleServer) Get(ctx context.Context, req *GetRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedSaleServer) Update(ctx context.Context, req *UpdateRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedSaleServer) Action(ctx context.Context, req *ActionRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Action not implemented")
}

func RegisterSaleServer(s *grpc.Server, srv SaleServer) {
	s.RegisterService(&_Sale_serviceDesc, srv)
}

func _Sale_Raw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleServer).Raw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/saleproto.Sale/Raw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleServer).Raw(ctx, req.(*RawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sale_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/saleproto.Sale/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sale_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/saleproto.Sale/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sale_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/saleproto.Sale/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sale_Action_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleServer).Action(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/saleproto.Sale/Action",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleServer).Action(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sale_serviceDesc = grpc.ServiceDesc{
	ServiceName: "saleproto.Sale",
	HandlerType: (*SaleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Raw",
			Handler:    _Sale_Raw_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Sale_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Sale_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Sale_Update_Handler,
		},
		{
			MethodName: "Action",
			Handler:    _Sale_Action_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
